/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  ug1Sidebar: [{ type: 'autogenerated', dirName: 'ug1' }],

  ug2Sidebar: [{ type: 'autogenerated', dirName: 'ug2' }],
 
  mw05Sidebar: [{ type: 'category', label: 'Most Wanted (2005)', link: { type: 'doc', id: 'mw05/index' }, collapsed: true, collapsible: true,
    items: [{ type: 'category', label: 'Most Wanted Any% Glitches', link: { type: 'doc', id: 'mw05/any/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'mw05/any/setup' },
      { type: 'doc', id: 'mw05/any/general' },
      { type: 'doc', id: 'mw05/any/simple-any' },
      { type: 'doc', id: 'mw05/any/inter-any' },
      { type: 'doc', id: 'mw05/any/info' },
      { type: 'doc', id: 'mw05/any/expert-any' } ] },
          { type: 'category', label: 'Most Wanted Any% No Major Glitches', link: { type: 'doc', id: 'mw05/nmg/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'mw05/nmg/setup' },
      { type: 'doc', id: 'mw05/nmg/general' },
      { type: 'doc', id: 'mw05/nmg/any' } ] },
          { type: 'category', label: 'Least Wanted Any%', link: { type: 'doc', id: 'mw05/lw/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'mw05/lw/setup' },
      { type: 'doc', id: 'mw05/lw/general' },
      { type: 'doc', id: 'mw05/lw/any' } ] } ] },

{ type: 'link', label: 'Speedrun.com page', href: 'https://www.speedrun.com/nfsmw05' },
{ type: 'link', label: 'Category Extensions page', href: 'https://www.speedrun.com/nfsmw05_ce' } ] ,

  lwmw05Sidebar: [{ type: 'category', label: 'Least Wanted Any%', link: { type: 'doc', id: 'mw05/lw/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'mw05/lw/setup', label: 'Setting up for speedruns' },
      { type: 'doc', id: 'mw05/lw/general', label: 'General information' },
      { type: 'doc', id: 'mw05/lw/any', label: 'Any% route' }, ], }, ],

  cSidebar: [{ type: 'category', label: 'Carbon', link: { type: 'doc', id: 'c/index' }, collapsed: true, collapsible: true,
    items: [
      { type: 'doc', id: 'c/setup', label: 'Setting up for speedruns' },
      { type: 'doc', id: 'c/general', label: 'General information' },
      { type: 'doc', id: 'c/any', label: 'Career Any% route' }, ], },
        
  {type: 'link', label: 'Speedrun.com page', href: 'https://www.speedrun.com/nfsc',},
  {type: 'link', label: 'Category Extensions page', href: 'https://www.speedrun.com/nfscce',}],

  psSidebar: [{ type: 'autogenerated', dirName: 'ps' }],

  ucSidebar: [{ type: 'autogenerated', dirName: 'uc' }],

  trSidebar: [{ type: 'autogenerated', dirName: 'tr' }],

};

export default sidebars;
